reddit:
  subreddits:
    - "Entrepreneur"
    - "startups"
    - "SaaS"
    - "smallbusiness"
    - "sidehustle"
    - "entrepreneurship"
    - "startup_ideas"
    - "Business_Ideas"
    - "growmybusiness"
    - "indiehackers"
    - "appideas"
    - "EntrepreneurRideAlong"
  keywords:
  # Self-Promotion
    - "time for self-promotion"
    - "self-promotion"
    - "promote your startup"
    - "plug your project"
    - "promote your business"
    - "showcase your startup"
    - "post your project"
    - "share your work"
    - "launching soon"

  # # Pain Points / Problems
    - "painful"
    - "biggest problem"
    - "biggest struggle"
    - "main challenge"
    - "biggest pain points"
    - "biggest pain point"
    - "pain point"
    - "roadblocks"
    - "frustrating issue"
    - "what's holding you back"
    - "why startups fail"
    - "what's stopping you from launching"
    - "why my startup failed"

    # Project / Building
    - "what projects are you working on?"
    - "what are you building right now"
    - "what are you working on?"
    - "what side project are you working on?"
    - "what have you launched?"
    - "working on something new?"
    - "what have you built?"
    - "show off your project"
    - "what's your latest project?"
    - "what's your current project?"
    - "what's your latest side hustle?"
    - "share what you've been working on"
    - "share what you've built"

    # SaaS & Idea Generation
    - "looking for saas ideas"
    - "saas ideas"
    - "I need an idea"
    - "I need a startup idea"
    - "I need a business idea"
    - "I need a SaaS idea"
    - "startup ideas"
    - "business ideas"
    - "what's a good saas idea?"
    - "any good startup ideas?"
    - "brainstorm startup ideas"
    - "anyone have saas ideas?"
    - "help me come up with an idea"

    # Growth / Marketing / Feedback
    - "how to get first users"
    - "how to get customers"
    - "how to grow my startup"
    - "how to grow my saas"
    - "feedback on my SaaS"
    - "how to market a saas"
    - "how to promote my startup"
  exclude_keywords:
    - "spam"

twitter:
  search_terms:
    - "business ideas"
    - "pain points"
  exclude_terms:
    - "spam"
    - "giveaway"

bluesky:
  feeds:
    - "buildinginpublic.bsky.social/aaafflelemvyy"  # Build in Public
    - "startygen.bsky.social/aaaoa5a2i37ji"         # Indie Hackers feed
    - "mallat.bsky.social/aaac3lfajk4re"      # MallaT feed
  keywords:
    - "share your"
    - "business ideas"
    - "startup ideas"
    - "side hustle"
    - "side project"
    - "ideas"
    - "idea"
    - "problem"
    - "problems"
    - "pain points"
    - "biggest"
    - "struggle"
