common_keywords: &common_keywords
  - self-promotion
  - self promotion
  - self-promote
  - self-promoting
  - self-promotional
  - share
  - shares
  - sharing
  - promote
  - promotes
  - promoting
  - promotion
  - promotional
  - plug
  - plugs
  - plugging
  - showcase
  - showcases
  - showcasing
  - problem
  - problems
  - problematic
  - struggle
  - struggles
  - struggling
  - challenge
  - challenges
  - challenging
  - roadblock
  - roadblocks
  - pain point
  - pain points
  - building
  - built
  - builds
  - latest project
  - latest projects
  - saas idea
  - saas ideas
  - startup idea
  - startup ideas
  - business idea
  - business ideas
  - ideas
  - idea

reddit:
  subreddits:
    - "Entrepreneur"
    - "startups"
    - "SaaS"
    - "smallbusiness"
    - "sidehustle"
    - "entrepreneurship"
    - "startup_ideas"
    - "Business_Ideas"
    - "growmybusiness"
    - "indiehackers"
    - "appideas"
    - "EntrepreneurRideAlong"
  keywords: *common_keywords
  exclude_keywords:
    - "spam"

twitter:
  communities:
    - "1471580197908586507"  # First community
    - "1493446837214187523"  # Second community
  keywords: *common_keywords
  exclude_terms:
    - "spam"
    - "giveaway"

bluesky:
  feeds:
    - "buildinginpublic.bsky.social/aaafflelemvyy"  # Build in Public
    - "startygen.bsky.social/aaaoa5a2i37ji"         # Indie Hackers feed
    - "mallat.bsky.social/aaac3lfajk4re"      # MallaT feed
  keywords: *common_keywords

youtube:
  channels:
    - "UCA-mWX9CvCTVFWRMb9bKc9w"  # Example channel ID
  keywords: *common_keywords
  exclude_keywords:
    - "spam"
    - "scam"

instagram:
  accounts:
    - "nathanbarry"
  keywords: *common_keywords
  exclude_keywords:
    - "spam"
    - "scam"
