common_keywords: &common_keywords
  - self-promotion
  - self promotion
  - self-promote
  - self-promoting
  - self-promotional
  - share
  - shares
  - sharing
  - promote
  - promotes
  - promoting
  - promotion
  - promotional
  - plug
  - plugs
  - plugging
  - showcase
  - showcases
  - showcasing
  - problem
  - problems
  - problematic
  - struggle
  - struggles
  - struggling
  - challenge
  - challenges
  - challenging
  - roadblock
  - roadblocks
  - pain point
  - pain points
  - building
  - built
  - builds
  - latest project
  - latest projects
  - saas idea
  - saas ideas
  - startup idea
  - startup ideas
  - business idea
  - business ideas
  - ideas
  - idea

reddit:
  subreddits:
    - "Entrepreneur"
    - "startups"
    - "SaaS"
    - "smallbusiness"
    - "sidehustle"
    - "entrepreneurship"
    - "startup_ideas"
    - "Business_Ideas"
    - "growmybusiness"
    - "indiehackers"
    - "appideas"
    - "EntrepreneurRideAlong"
  keywords: *common_keywords
  exclude_keywords:
    - "spam"

twitter:
  communities:
    - "1523269557816856576" # Indie Hackers
    - "1824090181827457380" # Tech Founders
    - "1669886565928300545" # SaaS & AI
    - "1808068384925360335" # Online Earning & Learning
    - "1498737511241158657" # start up founders and friends
    - "1497277132191547394" # Micro & Niche SaaS
    - "1492982239960969222" # Indie Makers
    - "1471580197908586507" # Building in Public
    - "1493446837214187523" # Start up Community
  keywords: *common_keywords
  exclude_terms:
    - "spam"
    - "giveaway"

bluesky:
  feeds:
    - "buildinginpublic.bsky.social/aaafflelemvyy"  # Build in Public
    - "startygen.bsky.social/aaaoa5a2i37ji"         # Indie Hackers feed
    - "mallat.bsky.social/aaac3lfajk4re"      # MallaT feed
  keywords: *common_keywords

youtube:
  channels:
    - "UCMo28ATCDU0Kn9dpilAF79Q"  # Simon Høiberg
    - "UCsg20ERGZt9eHVZRXROJSqg" # TheBrettWay
    - "UChhw6DlKKTQ9mYSpTfXUYqA" #starterstory
    - "UCHoBKQDRkJcOY2BO47q5Ruw" #MicroConf
    - "UCUseoG3kofRLS6WoUaL_15w" #TKKader
    - "UCEJ3Bv-zDYMmtACIyFo4nGQ" #dennisbabych
    - "UCrJrY9gMcbRL2APnFCXiuBQ" # wearenocode
    - "UC2JuGCGQ0c71WIyL_MlY5eg" # alexheiden
    - "UCVBNyvcHbffDw61L4sikLtQ" # stevencravotta
    - "UCfQk5qGOEO5cPPDFlQe2lFQ" # YourAverageTechBro
  keywords: *common_keywords
  exclude_keywords:
    - "spam"
    - "scam"

instagram:
  accounts:
    - "nathanbarry"
  keywords: *common_keywords
  exclude_keywords:
    - "spam"
    - "scam"
